Repository capstone-five-ai/Qtudy-FE, pull requests merged in 2024-06, with the labels that each got.

#99 feat: 디자인 추가 사항 반영 및 QA 반영
  src/apis/fileApi.ts
  src/assets/icons/trash.svg
  src/components/Form/QuizGenerationForm.tsx
  src/components/Icon/DeleteIcon.tsx
  src/components/InputField/FileNameInputField.tsx
  src/components/InputField/NameInputField.tsx
  src/components/InputField/QuizInputField.tsx
  src/components/Modal/DeleteItemModal.tsx
  src/components/SideBar/GenerateSidebar.tsx
  src/components/Toast/ToastMessage.tsx
  src/containers/CategoryDetailPage/CategorySidebar.tsx
  src/containers/CategoryPage/Category.tsx
  src/containers/CategoryPage/CategoryItem/CategoryQuizItem.tsx
  src/containers/CategoryPage/CategoryItem/CategorySummaryItem.tsx
  src/containers/HistoryPage/HistoryItem.tsx
  src/containers/QuizAIPage/GenerateSection.tsx
  src/containers/SummaryAIPage/GenerateSection.tsx
  src/containers/SummaryUserPage/GenerateSection.tsx
  src/hooks/useDebouncedValue.ts
  src/hooks/useDuplicatedFileName.ts
  src/hooks/useToast.ts
  src/pages/HIstoryPage.tsx
  src/recoils/atoms/toastState.ts
  src/routers/router.tsx
  src/types/quiz.type.ts
  src/types/summary.type.ts
Labels: 🐞 BugFix, ✨Feature, 🎨 Design

#103 hotfix: 빌드 오류 해결
  .github/ISSUE_TEMPLATE/feature-template.md
  src/components/Button/CheckBoxButton.tsx
  src/components/Modal/SaveToCategoryModal.tsx
  src/components/SideBar/DefaultSidebar.tsx
  src/components/SideBar/GenerateSidebar.tsx
  src/containers/CategoryDetailPage/CategorySidebar.tsx
  src/containers/QuizAIPage/ResultSection.tsx
  src/containers/QuizUserPage/ResultSection.tsx
  src/containers/SummaryAIPage/ResultSection.tsx
  src/containers/SummaryUserPage/ResultSection.tsx
  src/pages/CategoryQuizEditPage.tsx
  src/pages/CategorySummaryEditPage.tsx
Labels: 🐞 BugFix

#102 hotfix: 빌드 오류 해결
  src/components/Button/CheckBoxButton.tsx
  src/components/Modal/SaveToCategoryModal.tsx
  src/components/SideBar/DefaultSidebar.tsx
  src/components/SideBar/GenerateSidebar.tsx
  src/containers/CategoryDetailPage/CategorySidebar.tsx
  src/containers/QuizAIPage/ResultSection.tsx
  src/containers/QuizUserPage/ResultSection.tsx
  src/containers/SummaryAIPage/ResultSection.tsx
  src/containers/SummaryUserPage/ResultSection.tsx
  src/pages/CategoryQuizEditPage.tsx
  src/pages/CategorySummaryEditPage.tsx
Labels: 🐞 BugFix

#104 hotfix: 폴더명 대소문자 인식 못하는 문제 해결
  src/components/Sidebar/DefaultSidebar.tsx
  src/components/Sidebar/GenerateSidebar.tsx
Labels: 🐞 BugFix

#105 hotfix: 폴더명 대소문자 인식 못하는 문제 해결
  src/components/Sidebar/DefaultSidebar.tsx
  src/components/Sidebar/GenerateSidebar.tsx
Labels: 🐞 BugFix

#106 v0.1.2
  src/components/Navigation/TopNavigation.tsx
  src/pages/CategoryPage.tsx
Labels: 🌈 Deploy

#107 v0.1.3
  src/components/Navigation/MenuBar.tsx
  src/components/Tooltip/AnnouncementTooltip.tsx
  src/pages/CategoryPage.tsx
  src/pages/HistoryPage.tsx
Labels: 🌈 Deploy

#108 hotfix: 오픈 그래프 적용 안되는 문제 해결
  src/main.tsx
Labels: 🐞 BugFix

#109 hotfix: open graph 재적용
  index.html
Labels: 🐞 BugFix

#111 fix: 디자인 피드백 5차 반영
  src/components/Button/PlainButton.tsx
  src/components/Chip/FileTypeChip.tsx
  src/components/Form/QuizGenerationForm.tsx
  src/components/Header/ContentHeader.tsx
  src/components/InputField/CommentInputField.tsx
  src/components/InputField/FileNameInputField.tsx
  src/components/InputField/QuizInputField.tsx
  src/components/Modal/SaveToCategoryModal.tsx
  src/components/Sidebar/GenerateSidebar.tsx
  src/components/Wrapper/GenerateMethodWrapper.tsx
  src/containers/CategoryDetailPage/TopButtonBar.tsx
  src/containers/CategoryPage/Category.tsx
  src/containers/CategoryPage/CategorySection.tsx
  src/containers/CategoryPage/CategorySidebar.tsx
  src/containers/HistoryPage/HistoryItem.tsx
  src/containers/HistoryPage/HistoryList.tsx
  src/containers/QuizUserPage/GenerateSection.tsx
  src/pages/CategoryQuizEditPage.tsx
  src/pages/CategorySummaryDetailPage.tsx
  src/styles/typography.ts
  src/types/typography.type.ts
Labels: 🐞 BugFix, 🎨 Design

#112 v0.1.4
  src/components/Button/PlainButton.tsx
  src/components/Chip/FileTypeChip.tsx
  src/components/Form/QuizGenerationForm.tsx
  src/components/Header/ContentHeader.tsx
  src/components/InputField/CommentInputField.tsx
  src/components/InputField/FileNameInputField.tsx
  src/components/InputField/QuizInputField.tsx
  src/components/Modal/SaveToCategoryModal.tsx
  src/components/Sidebar/GenerateSidebar.tsx
  src/components/Wrapper/GenerateMethodWrapper.tsx
  src/containers/CategoryDetailPage/TopButtonBar.tsx
  src/containers/CategoryPage/Category.tsx
  src/containers/CategoryPage/CategorySection.tsx
  src/containers/CategoryPage/CategorySidebar.tsx
  src/containers/HistoryPage/HistoryItem.tsx
  src/containers/HistoryPage/HistoryList.tsx
  src/containers/QuizUserPage/GenerateSection.tsx
  src/pages/CategoryQuizEditPage.tsx
  src/pages/CategorySummaryDetailPage.tsx
  src/styles/typography.ts
  src/types/typography.type.ts
Labels: 🌈 Deploy

#113 fix: 디자인 피드백 5-1차 반영
  index.html
  src/components/Button/PlainButton.tsx
  src/components/Card/GenerateMethodCard.tsx
  src/components/Navigation/MenuBar.tsx
  src/components/Navigation/TopNavigation.tsx
  src/containers/CategoryPage/CategorySidebar.tsx
  src/containers/QuizUserPage/GenerateSection.tsx
  src/pages/CategoryQuizEditPage.tsx
  src/pages/LoginPage.tsx
  src/pages/SelectServicePage.tsx
  src/styles/color.ts
Labels: 🐞 BugFix, 🎨 Design

#115 fix: 디자인 피드백 5-1차 반영
  index.html
  src/components/Button/PlainButton.tsx
  src/components/Card/GenerateMethodCard.tsx
  src/components/Navigation/MenuBar.tsx
  src/components/Navigation/TopNavigation.tsx
  src/containers/CategoryPage/CategorySidebar.tsx
  src/containers/QuizUserPage/GenerateSection.tsx
  src/pages/CategoryQuizEditPage.tsx
  src/pages/LoginPage.tsx
  src/pages/SelectServicePage.tsx
  src/styles/color.ts
Labels: 🐞 BugFix, 🎨 Design

#117 fix: 디자인 피드백 5-2차 반영
  src/components/Card/GenerateMethodCard.tsx
  src/components/Form/QuizGenerationForm.tsx
  src/components/Navigation/MenuBar.tsx
  src/components/Navigation/TopNavigation.tsx
  src/containers/LoginPage/BrandMotion.tsx
  src/pages/SelectServicePage.tsx
Labels: 🐞 BugFix, 🎨 Design

#118 v0.1.6
  src/components/Card/GenerateMethodCard.tsx
  src/components/Form/QuizGenerationForm.tsx
  src/components/Navigation/MenuBar.tsx
  src/components/Navigation/TopNavigation.tsx
  src/containers/LoginPage/BrandMotion.tsx
  src/pages/SelectServicePage.tsx
Labels: 🌈 Deploy

#122 design: 디자인 변경사항 반영
  index.html
  src/assets/logo/qtudy.svg
  src/components/Button/GenerateButton.tsx
  src/components/Button/PlainButton.tsx
  src/components/Button/SaveToCategoryButton.tsx
  src/components/Card/GenerateMethodCard.tsx
  src/components/Form/QuizGenerationForm.tsx
  src/components/Loader/GenerateLoader.tsx
  src/components/Loader/SuspenseLoading.tsx
  src/components/Modal/DeleteItemModal.tsx
  src/components/Modal/ShareLinkModal.tsx
  src/components/Navigation/MenuBar.tsx
  src/components/Navigation/TopNavigation.tsx
  src/containers/CategoryDetailPage/CategorySidebar.tsx
  src/containers/CategoryPage/CategoryItem/CategoryItem.style.ts
  src/containers/LoginPage/BrandMotion.tsx
  src/containers/QuizAIPage/ResultSection.tsx
  src/containers/QuizUserPage/ResultSection.tsx
  src/containers/SelectServicePage/Card.tsx
  src/containers/SummaryAIPage/ResultSection.tsx
  src/containers/SummaryUserPage/ResultSection.tsx
  src/pages/CategoryPage.tsx
  src/pages/QuizAIPage.tsx
  src/pages/QuizUserPage.tsx
  src/pages/SummaryAIPage.tsx
  src/pages/SummaryUserPage.tsx
  src/routers/router.tsx
  src/styles/color.ts
Labels: 🎨 Design

#123 v0.1.7
  index.html
  src/assets/logo/qtudy.svg
  src/components/Button/GenerateButton.tsx
  src/components/Button/PlainButton.tsx
  src/components/Button/SaveToCategoryButton.tsx
  src/components/Card/GenerateMethodCard.tsx
  src/components/Form/QuizGenerationForm.tsx
  src/components/Loader/GenerateLoader.tsx
  src/components/Loader/SuspenseLoading.tsx
  src/components/Modal/DeleteItemModal.tsx
  src/components/Modal/ShareLinkModal.tsx
  src/components/Navigation/MenuBar.tsx
  src/components/Navigation/TopNavigation.tsx
  src/containers/CategoryDetailPage/CategorySidebar.tsx
  src/containers/CategoryPage/CategoryItem/CategoryItem.style.ts
  src/containers/LoginPage/BrandMotion.tsx
  src/containers/QuizAIPage/ResultSection.tsx
  src/containers/QuizUserPage/ResultSection.tsx
  src/containers/SelectServicePage/Card.tsx
  src/containers/SummaryAIPage/ResultSection.tsx
  src/containers/SummaryUserPage/ResultSection.tsx
  src/pages/CategoryPage.tsx
  src/pages/QuizAIPage.tsx
  src/pages/QuizUserPage.tsx
  src/pages/SummaryAIPage.tsx
  src/pages/SummaryUserPage.tsx
  src/routers/router.tsx
  src/styles/color.ts
Labels: 🌈 Deploy

#124 Design/#121/design improve
  src/components/Form/QuizGenerationForm.tsx
  src/components/InputField/CategoryInputFieldContainer.tsx
  src/components/Modal/NewCategoryModal.tsx
  src/containers/QuizAIPage/GenerateSection.tsx
  src/containers/SummaryAIPage/GenerateSection.tsx
  src/containers/SummaryUserPage/GenerateSection.tsx
Labels: 🎨 Design

#125 v0.1.7
  src/components/Form/QuizGenerationForm.tsx
  src/components/InputField/CategoryInputFieldContainer.tsx
  src/components/Modal/NewCategoryModal.tsx
  src/containers/QuizAIPage/GenerateSection.tsx
  src/containers/SummaryAIPage/GenerateSection.tsx
  src/containers/SummaryUserPage/GenerateSection.tsx
Labels: 🌈 Deploy

#126 design: 디자인 변경사항 반영
  src/components/Button/PlainButton.tsx
  src/components/Button/SaveToCategoryButton.tsx
  src/containers/CategoryDetailPage/CategorySidebar.tsx
  src/containers/QuizAIPage/ResultSection.tsx
  src/containers/QuizUserPage/ResultSection.tsx
  src/containers/SummaryAIPage/ResultSection.tsx
  src/containers/SummaryUserPage/ResultSection.tsx
  src/pages/CategorySummaryEditPage.tsx
Labels: 🎨 Design

#127 v0.1.7
  src/components/Button/PlainButton.tsx
  src/components/Button/SaveToCategoryButton.tsx
  src/containers/CategoryDetailPage/CategorySidebar.tsx
  src/containers/QuizAIPage/ResultSection.tsx
  src/containers/QuizUserPage/ResultSection.tsx
  src/containers/SummaryAIPage/ResultSection.tsx
  src/containers/SummaryUserPage/ResultSection.tsx
  src/pages/CategorySummaryEditPage.tsx
Labels: 🌈 Deploy

#128 hotfix: padding 오타 수정 및 배경색 삭제
  src/pages/CategorySummaryDetailPage.tsx
  src/pages/CategorySummaryEditPage.tsx
Labels: 🐞 BugFix

#129 hotfix: 요약 편집 시 파일 중복 체크 안하는 문제 해결
  src/components/Button/PlainButton.tsx
  src/hooks/useDuplicatedFileName.ts
  src/pages/CategorySummaryEditPage.tsx
Labels: 🐞 BugFix

#130 hotfix: 편집 아이콘 클릭 시 input 창이 focus 되도록 수정
  src/components/InputField/CommentInputField.tsx
  src/components/InputField/QuizInputField.tsx
  src/containers/CategoryPage/Category.tsx
  src/containers/HistoryPage/HistoryItem.tsx
Labels: 🐞 BugFix
